version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: 1
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # MQTT брокер
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  # Zookeeper (для Kafka)
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "raw_material_data:1:1,bottle_forming_data:1:1,cooling_data:1:1,quality_data:1:1,packaging_data:1:1,alerts:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Основное приложение
  app:
    build: .
    depends_on:
      - postgres
      - kafka
      - mosquitto
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=1
      - DB_PASS=1
      - DB_NAME=production
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - MQTT_QOS=1
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_MAX_BATCH_SIZE=16384
      - KAFKA_LINGER_MS=100
      - SECRET_KEY=abc
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs



volumes:
  postgres_data: