version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pet_bottle_automation
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # MQTT брокер
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  # Zookeeper (для Kafka)
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "raw_material_data:1:1,bottle_forming_data:1:1,cooling_data:1:1,quality_data:1:1,packaging_data:1:1,alerts:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Основное приложение
  app:
    build: .
    depends_on:
      - postgres
      - kafka
      - mosquitto
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/pet_bottle_automation
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs

  # Симулятор датчиков
  simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883

volumes:
  postgres_data: